generation: # Parameter to generate candidate pose
  distance: 0.45 # Distance to impose between the camera and the calibration marker
  angles:        # Angles to take on x, y and z axis in order to sample candidate pose, in a grid manner.
    - 0
    - np.pi/6
    - -np.pi/6
    - np.pi/4
    - -np.pi/4
    - np.pi/3
    - -np.pi/3
    - np.pi/2
    - -np.pi/2
marker_pose: # Aruco calibration tag pose in world frame
  xyz: [-0.495, 0, 0.008] # position
  rpy: [0, 0, 0]          # orientation
output_paths:
  poses_all: files/experiment/pose_generation/poses_sample.pkl
  poses_reachable: files/experiment/pose_generation/poses_reachable.pkl
  poses_reachable_ordered: files/experiment/pose_generation/poses_reachable_ordered.pkl
  poses_export: files/experiment/pose_generation/exported_poses/
  measures: files/experiment/measures/

n_final_poses: 20 # Number of poses to keep for the final calibration